// ─── PDF Export ──────────────────────────────────────────────────────────
// Generate a professional PDF report from an AnalysisResult.

import { jsPDF } from 'jspdf';
import { AnalysisResult } from '../types';

export function exportPDF(result: AnalysisResult): void {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();
  const margin = 20;
  const cw = pw - 2 * margin;
  let y = 20;

  const wrap = (text: string, x: number, yy: number, maxW: number, lh = 5) => {
    const lines = doc.splitTextToSize(text, maxW);
    doc.text(lines, x, yy);
    return yy + lines.length * lh;
  };

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(59, 130, 246);
  doc.text('Codalyzer', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  const ts = new Date().toLocaleString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
  });
  doc.text(`Generated: ${ts}`, margin, y);
  y += 10;

  doc.setDrawColor(51, 65, 85);
  doc.line(margin, y, pw - margin, y);
  y += 10;

  // File info
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`Analysis Report: ${result.fileName}`, margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Language: ${result.language}`, margin, y);
  y += 12;

  // Metrics
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Complexity Analysis', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);

  const metrics = [
    ['Time (Best)', result.timeComplexity.best.notation, result.timeComplexity.best.rating],
    ['Time (Average)', result.timeComplexity.average.notation, result.timeComplexity.average.rating],
    ['Time (Worst)', result.timeComplexity.worst.notation, result.timeComplexity.worst.rating],
    ['Space', result.spaceComplexity.notation, result.spaceComplexity.rating],
  ];
  for (const [label, val, rating] of metrics) {
    doc.text(`${label}: ${val} (${rating})`, margin, y);
    y += 6;
  }
  y += 6;

  // Issues
  if (result.issues.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Issues Detected', margin, y);
    y += 8;

    doc.setFontSize(9);
    for (let i = 0; i < result.issues.length; i++) {
      const issue = result.issues[i];
      doc.setFont('helvetica', 'bold');
      doc.text(`${i + 1}. [${issue.type}] ${issue.title}`, margin, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      y = wrap(issue.description, margin + 5, y, cw - 5, 4);
      y += 4;

      if (y > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        y = 20;
      }
    }
    y += 4;
  }

  // Summary
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Summary', margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  y = wrap(result.summary, margin, y, cw);
  y += 10;

  // Source code
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Source Code', margin, y);
  y += 8;

  const codeLines = result.sourceCode.split('\n');
  const codeH = Math.min(codeLines.length * 4 + 10, 100);

  if (y + codeH > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = 20;
  }

  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, cw, codeH, 2, 2, 'F');

  doc.setFontSize(8);
  doc.setFont('courier', 'normal');
  doc.setTextColor(51, 65, 85);

  let cy = y + 5;
  const maxLines = 20;
  for (const line of codeLines.slice(0, maxLines)) {
    doc.text(line.length > 80 ? line.substring(0, 77) + '...' : line, margin + 3, cy);
    cy += 4;
  }
  if (codeLines.length > maxLines) {
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 116, 139);
    doc.text(`... and ${codeLines.length - maxLines} more lines`, margin + 3, cy);
  }
  y += codeH + 15;

  // Disclaimer
  if (y > doc.internal.pageSize.getHeight() - 30) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(251, 191, 36);
  doc.setFillColor(254, 252, 232);
  doc.roundedRect(margin, y, cw, 20, 2, 2, 'FD');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(146, 64, 14);
  doc.text('⚠ Important Disclaimer', margin + 5, y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(113, 63, 18);
  wrap(
    'This analysis was generated by AI and may contain inaccuracies. Always review and verify the results manually. The complexity estimations are based on static code analysis and may not reflect actual runtime performance.',
    margin + 5, y + 11, cw - 10, 3,
  );

  doc.save(`codalyzer-${result.fileName.replace(/\.[^/.]+$/, '')}.pdf`);
}
